### ISSUE TITLE
zeu不错

### ISSUE THREAD

**Issue by kener** [shzlw/zeu#1]
嘿，你好。我是蚂蚁金服数据可视化团队的御术，朋友可能会叫我林峰多一些，以前在百度，写了 ECharts，目前在带蚂蚁的数据可视化团队，负责 AntV 以及相关的一个可视分析产品，看到zeu.js了，很不错，不知道最近是否有换工作的考虑，我这需要数据可视化工程师，求加入，如果感兴趣，随时与我联系微博 https://weibo.com/kenerlinfeng，这里有些关于团队更详细的介绍 https://www.zhihu.com/question/276044122/answer/385588637

**Comment by shzlw** [comment]
久仰大名，ECharts和AntV都非常厉害，我主写后端，JS写的不好，还在学习中，希望以后有机会加入:)

**Comment by kener** [comment]
厉害，前端副业写出来，期待有缘~
