### ISSUE TITLE
awesome library! shall we need option to disable VolumeMeter value blink?

### ISSUE THREAD

**Issue by postgetme** [shzlw/zeu#3]

**Comment by shzlw** [comment]
Thanks. Instead of adding an option to enable/disable it, I removed the blink function in volume meter totally. For all widgets, there is actually an [Alert](https://shzlw.github.io/zeu/docs/configuration.html) function now which you can use to display a blinking alert dialog on and off.

**Comment by postgetme** [comment]
that's awesome, thanks.
