### ISSUE TITLE
Set value of a heartbeat

### ISSUE THREAD

**Issue by Coriou** [shzlw/zeu#4]
Hey. Beautiful library. Just wondering if the heartbeat value is controllable ? Thanks

**Comment by shzlw** [comment]
Thanks. I am not clear on what value you'd like to set. If you take a look at [heartbeat example](https://shzlw.github.io/zeu/docs/heartbeat.html), the frequency of triggering a heartbeat can be controlled by calling heartbeat.beat(). That function also accepts a space parameter to control the size of the shape. Maybe you can compute the space value based on your "heartbeat value"?

**Comment by Coriou** [comment]
Yes, I'm sorry, my bad. I didn't understand the "chart" correctly. I was looking for a way to set a positive or negative value (above or below the central axis).
